### ISSUE TITLE
My laptop is broken...

### ISSUE THREAD

**Issue by NeoWu1216** [Zonglin-Li6565/DoNotStar#1]

**Comment by Zonglin-Li6565** [comment]
That's expected outcome.

**Comment by apsun** [comment]
Where is this behavior documented? Can you provide a link?

**Comment by Zonglin-Li6565** [comment]
https://i.ytimg.com/vi/91v7TX1PcWU/hqdefault.jpg

**Comment by apsun** [comment]
Looks like a bug; we shouldn't be applying breaking behavior to laptops, only desktops. I suggest adding a `boolean shouldBreak(IComputer c)` check.

**Comment by Zonglin-Li6565** [comment]
No. The computer shown in the spec is a metonymy of the basic level concept Computer. Both desktop and laptop computers are subordinate level concepts of that basic level concept. So I guess there is no problem.
